<?php


namespace cobra_salsa;


class ResumenObject
{
    public $nombre_deudor = '';
    public $domicilio_deudor = '';
    public $colonia_deudor = '';
    public $ciudad_deudor = '';
    public $estado_deudor = '';
    public $cp_deudor = '';
    public $plano_guia_roji = '';
    public $cuadrante_guia_roji = '';
    public $tel_1 = '';
    public $tel_2 = '';
    public $tel_3 = '';
    public $tel_4 = '';
    public $nombre_deudor_alterno = '';
    public $domicilio_deudor_alterno = '';
    public $colonia_deudor_alterno = '';
    public $ciudad_deudor_alterno = '';
    public $estado_deudor_alterno = '';
    public $cp_deudor_alterno = '';
    public $tel_1_alterno = '';
    public $tel_2_alterno = '';
    public $tel_3_alterno = '';
    public $tel_4_alterno = '';
    public $plano_guia_roji_alterno = '';
    public $cuadrante_guia_roji_alterno = '';
    public $status_aarsa = '';
    public $avapar = '';
    public $parentesco_ref_1;
    public $nombre_referencia_1;
    public $domicilio_referencia_1;
    public $colonia_referencia_1;
    public $ciudad_referencia_1;
    public $estado_referencia_1;
    public $cp_referencia_1;
    public $tel_1_ref_1;
    public $tel_2_ref_1;
    public $parentesco_ref_2;
    public $nombre_referencia_2;
    public $domicilio_referencia_2;
    public $colonia_referencia_2;
    public $ciudad_referencia_2;
    public $estado_referencia_2;
    public $cp_referencia_2;
    public $tel_1_ref_2;
    public $tel_2_ref_2;
    public $parentesco_ref_3;
    public $nombre_referencia_3;
    public $domicilio_referencia_3;
    public $colonia_referencia_3;
    public $ciudad_referencia_3;
    public $estado_referencia_3;
    public $cp_referencia_3;
    public $tel_1_ref_3;
    public $tel_2_ref_3;
    public $parentesco_ref_4;
    public $nombre_referencia_4;
    public $originacion;
    public $multiestrategia;
    public $ciudad_referencia_4;
    public $estado_referencia_4;
    public $cp_referencia_4;
    public $tel_1_ref_4;
    public $tel_2_ref_4;
    public $domicilio_laboral;
    public $colonia_laboral;
    public $ciudad_laboral;
    public $estado_laboral;
    public $cp_laboral;
    public $tel_1_laboral;
    public $tel_2_laboral;
    public $saldo_corriente;
    public $fecha_de_actualizacion;
    public $numero_de_cuenta;
    public $numero_de_credito;
    public $contrato;
    public int $saldo_total = 0;
    public int $saldo_vencido = 0;
    public int $saldo_descuento_1 = 0;
    public int $saldo_descuento_2 = 0;
    public $fecha_corte;
    public $fecha_limite;
    public $fecha_de_ultimo_pago;
    public $monto_ultimo_pago;
    public $producto;
    public $subproducto;
    public $cliente;
    public $status_de_credito;
    public $pagos_vencidos;
    public $monto_adeudado;
    public $fecha_de_asignacion;
    public $fecha_de_deasignacion;
    public $cuenta_concentradora_1;
    public $saldo_cuota;
    public $email_deudor;

    /**
     * @var int
     */
    public int $id_cuenta;
    public $nss;
    public $rfc_deudor;
    public $telefonos_marcados;
    public $tel_1_verif;
    public $tel_2_verif;
    public $tel_3_verif;
    public $tel_4_verif;
    public $telefono_de_ultimo_contacto;
    public int $dias_vencidos = 0;
    public $ejecutivo_asignado_call_center;
    public $ejecutivo_asignado_domiciliario;
    public $prioridad_de_gestion;
    public $NRPP;
    public $parentesco_aval;
    public $localizar;
    public $fecha_ultima_gestion;
    public $empresa;
    public $timelock;
    public $locker = '';
    public $fecha_convenio;
    public int $especial = 0;
    public $direccion_nueva;
    public $norobot;
}