<?php


namespace cobra_salsa;


class ResumenObject
{
    public string $nombre_deudor = '';
    public string $domicilio_deudor = '';
    public string $colonia_deudor = '';
    public string $ciudad_deudor = '';
    public string $estado_deudor = '';
    public string $cp_deudor = '';
    public string $plano_guia_roji = '';
    public string $cuadrante_guia_roji = '';
    public string $tel_1 = '';
    public string $tel_2 = '';
    public string $tel_3 = '';
    public string $tel_4 = '';
    public string $nombre_deudor_alterno = '';
    public string $domicilio_deudor_alterno = '';
    public string $colonia_deudor_alterno = '';
    public string $ciudad_deudor_alterno = '';
    public string $estado_deudor_alterno = '';
    public string $cp_deudor_alterno = '';
    public string $tel_1_alterno = '';
    public string $tel_2_alterno = '';
    public string $tel_3_alterno = '';
    public string $tel_4_alterno = '';
    public string $plano_guia_roji_alterno = '';
    public string $cuadrante_guia_roji_alterno = '';
    public string $status_aarsa = '';
    public string $avapar = '';
    public string $parentesco_ref_1;
    public string $nombre_referencia_1;
    public string $domicilio_referencia_1;
    public string $colonia_referencia_1;
    public string $ciudad_referencia_1;
    public string $estado_referencia_1;
    public string $cp_referencia_1;
    public string $tel_1_ref_1;
    public string $tel_2_ref_1;
    public string $parentesco_ref_2;
    public string $nombre_referencia_2;
    public string $domicilio_referencia_2;
    public string $colonia_referencia_2;
    public string $ciudad_referencia_2;
    public string $estado_referencia_2;
    public string $cp_referencia_2;
    public string $tel_1_ref_2;
    public string $tel_2_ref_2;
    public string $parentesco_ref_3;
    public string $nombre_referencia_3;
    public string $domicilio_referencia_3;
    public string $colonia_referencia_3;
    public string $ciudad_referencia_3;
    public string $estado_referencia_3;
    public string $cp_referencia_3;
    public string $tel_1_ref_3;
    public string $tel_2_ref_3;
    public string $parentesco_ref_4;
    public string $nombre_referencia_4;
    public string $originacion;
    public string $multiestrategia;
    public string $ciudad_referencia_4;
    public string $estado_referencia_4;
    public string $cp_referencia_4;
    public string $tel_1_ref_4;
    public string $tel_2_ref_4;
    public string $domicilio_laboral;
    public string $colonia_laboral;
    public string $ciudad_laboral;
    public string $estado_laboral;
    public string $cp_laboral;
    public string $tel_1_laboral;
    public string $tel_2_laboral;
    public string $saldo_corriente;
    public string $fecha_de_actualizacion;
    public string $numero_de_cuenta;
    public string $numero_de_credito;
    public string $contrato;
    public int $saldo_total = 0;
    public int $saldo_vencido = 0;
    public int $saldo_descuento_1 = 0;
    public int $saldo_descuento_2 = 0;
    public string $fecha_corte;
    public string $fecha_limite;
    public string $fecha_de_ultimo_pago;
    public string $monto_ultimo_pago;
    public string $producto;
    public string $subproducto;
    public string $cliente;
    public string $status_de_credito;
    public string $pagos_vencidos;
    public string $monto_adeudado;
    public string $fecha_de_asignacion;
    public string $fecha_de_deasignacion;
    public string $cuenta_concentradora_1;
    public string $saldo_cuota;
    public string $email_deudor;

    /**
     * @var int
     */
    public int $id_cuenta;
    public string $nss;
    public string $rfc_deudor;
    public string $telefonos_marcados;
    public string $tel_1_verif;
    public string $tel_2_verif;
    public string $tel_3_verif;
    public string $tel_4_verif;
    public string $telefono_de_ultimo_contacto;
    public int $dias_vencidos = 0;
    public string $ejecutivo_asignado_call_center;
    public string $ejecutivo_asignado_domiciliario;
    public string $prioridad_de_gestion;
    public string $NRPP;
    public string $parentesco_aval;
    public string $localizar;
    public string $fecha_ultima_gestion;
    public string $empresa;
    public string $timelock;
    public string $locker = '';
    public string $fecha_convenio;
    public int $especial = 0;
    public string $direccion_nueva;
    public string $norobot;
}